version: '3.1'

services:
  backend:
    image: phenomenon
    ports:
      - "5000:5000"
    networks:
      - backend
    environment:
      DATABASE_URL: postgres://phenomenon:password@db/phenomenon
      DOMAIN: example.com
      PORT: 5000
      JOB_WORKERS: 1
      RUST_LOG: debug

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: phenomenon
      POSTGRES_USER: phenomenon
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend: {}

volumes:
  db-data:
